openapi: 3.0.3
info:
  title: details
  description: |-
    Details API
  version: 'v1'
servers:
  - url: "http://localhost:8080"
  - url: "https://microcks-microcks.apps.cluster-l9nz6.dynamic.redhatworkshops.io/rest/details/v1"
paths: {}
